### ISSUE TITLE
Add home page

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [SuspiciousLookingOwl/web-frameworks-benchmark#1]
Add home page similar to  [the-benchmarker/web-frameworks readme](https://github.com/the-benchmarker/web-frameworks#readme)

(As requested in https://github.com/the-benchmarker/web-frameworks/pull/4194)

**Comment by SuspiciousLookingOwl** [comment]
Hi @waghanza

Which part of the [README](https://github.com/the-benchmarker/web-frameworks#readme) do you want me to include on the home page?

I don't think it makes sense to include [Usage](https://github.com/the-benchmarker/web-frameworks#usage) and [Results](https://github.com/the-benchmarker/web-frameworks#results-2021-04-20) table from the README on the home page.

I'm planning to move the table to other page, current route:
- `/` and `/results` -> Data table (`/results` is an alias)
- `/compare` -> Compare framework page

new route:
- `/` -> Home page, contains the [motivation](https://github.com/the-benchmarker/web-frameworks#motivation) and [requirements](https://github.com/the-benchmarker/web-frameworks#requirements), and also some other general information like  hardware used, last update date, and link to [the-benchmarker/web-frameworks](https://github.com/the-benchmarker/web-frameworks) repository
- `/results` -> Data table
- `/compare` -> Compare framework page

What do you think?

**Comment by waghanza** [comment]
Alls good for me. The main idea is for me to :
- remove result table from README
- include you repo in the organisation
- link you awesome work on the README

What is missing from the static table here, is the ability to filter/sort, and in this case the table you create is 👍🏻 

Be aware that the numbers displayed are already an average (since the scenario here make 3 requests) => maybe a bad idea, btw (perhaps better to do a percentile or something like that)

**Comment by SuspiciousLookingOwl** [comment]
Ahh I see, that makes more sense.

> Be aware that the numbers displayed are already an average (since the scenario here make 3 requests) => maybe a bad idea, btw (perhaps better to do a percentile or something like that)

I will update the data table later so it will shows more data (min max avg latency, 50 75 90 99 99.999th percentile), will be tracked in #2

**Comment by SuspiciousLookingOwl** [comment]
@waghanza a bit off topic, but do you mind if I use The Benchmarker icon as the website icon?
![1](https://avatars.githubusercontent.com/u/40886133?s=200&v=4)

**Comment by waghanza** [comment]
Thanks for asking. I prefer to transfer you repository here before (also since I'm not the author of this visual)

**Comment by SuspiciousLookingOwl** [comment]
No worries, I will stick with React icon for now 😂
