### ISSUE TITLE
Outline exact versions

### ISSUE THREAD

**Issue by lcmgh** [SuspiciousLookingOwl/web-frameworks-benchmark#37]
https://web-frameworks-benchmark.netlify.app/compare?f=axum

Minor version bumps can also include performance improvements so it would be nice to see the full version number reflected in the test results.

**Comment by waghanza** [comment]
Indeed, patch level version could add some improvements (in term of performances), but :
- generally minor
- using patch level could be complicated, as for reading result page
- it adds a lot  of complexity to maintenance
